baseURL: /
languageCode: en-us
title: Elkesensor
DefaultContentLanguage: ee

# See https://feathericons.com/
# The value of pre is the icon name

menu:
  main:
    - name: Ettevõttest
      identifier: ettevõttest
      url: /
      weight: 1
    - name: Partnerid
      identifier: partnerid
      url: /partnerid/
      weight: 2
    - name: Tooted
      identifier: tooted
      url: /tooted/
      weight: 3
    - name: Kontakt
      identifier: contact
      url: /kontakt/
      weight: 4

Languages:
  ee:
    LanguageCode: ee
    LanguageName: Estonia
    weight: 1
  en:
    LanguageCode: en
    LanguageName: English
    weight: 2
    
    menu:
      main:
        - name: About
          identifier: ettevõttest
          url: /
          weight: 1
        - name: Partners
          identifier: partnerid
          url: /partnerid/
          weight: 3
        - name: Products
          identifier: tooted
          url: /tooted/
          weight: 5
        - name: Contact
          identifier: kontakt
          url: /kontakt/
          weight: 6




# menu:
#   nav:
#   - name: Ettevõttest
#     pre: 
#     url: /
#     weight: 1
#   - name: Partnerid
#     pre: 
#     url: /partnerid/
#     weight: 2
#   - name: Tooted
#     pre: 
#     url: /tooted/
#     weight: 3
#   - name: Kontakt
#     pre: 
#     url: /kontakt/
#     weight: 4


params:
  showActiveNav: true 
  footerText: Copyright © 2017 Elke Sensor OÜ. Kõik õigused kaitstud. by HansaNet
  contact:
    title: Kontakt
    form:
      name:
        text: Nimi
        error: Palun sisestage oma nimi
      email:
        text: Email Aadress
        error: Palun sisestage oma meili aadress
      message:
        text: Sõnum
        error: Palun sisestage oma sõnum
      button:
        text: Saada
  email: yourformspree@emailhereplease.com

          


